# Generated by Django 3.2.21 on 2024-01-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_menu_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='detail',
            field=models.TextField(blank=True),
        ),
    ]
