# Generated by Django 3.2.21 on 2024-01-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_menu_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='zahra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
