# Generated by Django 3.2.21 on 2024-01-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_zahra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('detail', models.TextField(blank=True)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='zahra',
        ),
    ]
