# Generated by Django 3.2.21 on 2024-01-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240123_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saba',
        ),
        migrations.AddField(
            model_name='menu',
            name='quantity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
