# Generated by Django 3.2.21 on 2024-01-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='material',
            name='drinkType',
        ),
        migrations.RemoveField(
            model_name='material',
            name='primeryMaterial',
        ),
        migrations.RemoveField(
            model_name='material',
            name='torshi',
        ),
        migrations.AddField(
            model_name='material',
            name='quantity',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
